core:
    ApplicationManager:
        appPath: resources/toolbar/src/tb/apps
        active: main
        route: ""
        applications:

            main:
                label: Main
                config:
                    mainRoute: appMain/index

            layout:
                label: Layout
                config:
                    mainRoute: appLayout/home

            content:
                label: Edition du contenu
                config: []

            bundle:
                label: Bundle
                config:
                    mainRoute: bundle/index

            page:
                label: Page
                config:
                    mainRoute: page/index

            contribution:
                label: Contribution
                config:
                    mainRoute: contribution/index
    
wrapper_toolbar_selector: '#bb5-ui'
        
component:
    
    logger: 
        level: 8
        mode: 'devel'
        
    exceptions-viewer: 
        show: true
        
    translator: 
        base: 'resources/toolbar/src/tb/i18n/'
        locale: 'en_US'
        
        
unclickable_contents: 
    contents: 
        - 'Element/Text'
        - 'Element/Attachment'
        - 'Element/Date'
        - 'Element/File'
        - 'Element/Image'
        - 'Element/Keyword'
        - 'Element/Link'
        - 'Element/Select'
        - 'ContentSet'
